/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnneesRouteImport } from './routes/annees'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ElevesRouteImport } from './routes/eleves'
import { Route as MatieresRouteImport } from './routes/matieres'
import { Route as NotesRouteImport } from './routes/notes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnneesRoute = AnneesRouteImport.update({
  id: '/annees',
  path: '/annees',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesRoute = ElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => rootRouteImport,
} as any)
const MatieresRoute = MatieresRouteImport.update({
  id: '/matieres',
  path: '/matieres',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annees': typeof AnneesRoute
  '/classes': typeof ClassesRoute
  '/eleves': typeof ElevesRoute
  '/matieres': typeof MatieresRoute
  '/notes': typeof NotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annees': typeof AnneesRoute
  '/classes': typeof ClassesRoute
  '/eleves': typeof ElevesRoute
  '/matieres': typeof MatieresRoute
  '/notes': typeof NotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annees': typeof AnneesRoute
  '/classes': typeof ClassesRoute
  '/eleves': typeof ElevesRoute
  '/matieres': typeof MatieresRoute
  '/notes': typeof NotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/annees' | '/classes' | '/eleves' | '/matieres' | '/notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/annees' | '/classes' | '/eleves' | '/matieres' | '/notes'
  id:
    | '__root__'
    | '/'
    | '/annees'
    | '/classes'
    | '/eleves'
    | '/matieres'
    | '/notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnneesRoute: typeof AnneesRoute
  ClassesRoute: typeof ClassesRoute
  ElevesRoute: typeof ElevesRoute
  MatieresRoute: typeof MatieresRoute
  NotesRoute: typeof NotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annees': {
      id: '/annees'
      path: '/annees'
      fullPath: '/annees'
      preLoaderRoute: typeof AnneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves': {
      id: '/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof ElevesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matieres': {
      id: '/matieres'
      path: '/matieres'
      fullPath: '/matieres'
      preLoaderRoute: typeof MatieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnneesRoute: AnneesRoute,
  ClassesRoute: ClassesRoute,
  ElevesRoute: ElevesRoute,
  MatieresRoute: MatieresRoute,
  NotesRoute: NotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
