/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnneesRouteImport } from './routes/annees'
import { Route as BulletinsRouteImport } from './routes/bulletins'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as ElevesRouteImport } from './routes/eleves'
import { Route as MatieresRouteImport } from './routes/matieres'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ParametresRouteImport } from './routes/parametres'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnneesRoute = AnneesRouteImport.update({
  id: '/annees',
  path: '/annees',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinsRoute = BulletinsRouteImport.update({
  id: '/bulletins',
  path: '/bulletins',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesRoute = ElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => rootRouteImport,
} as any)
const MatieresRoute = MatieresRouteImport.update({
  id: '/matieres',
  path: '/matieres',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annees': typeof AnneesRoute
  '/bulletins': typeof BulletinsRoute
  '/classes': typeof ClassesRoute
  '/eleves': typeof ElevesRoute
  '/matieres': typeof MatieresRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annees': typeof AnneesRoute
  '/bulletins': typeof BulletinsRoute
  '/classes': typeof ClassesRoute
  '/eleves': typeof ElevesRoute
  '/matieres': typeof MatieresRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annees': typeof AnneesRoute
  '/bulletins': typeof BulletinsRoute
  '/classes': typeof ClassesRoute
  '/eleves': typeof ElevesRoute
  '/matieres': typeof MatieresRoute
  '/notes': typeof NotesRoute
  '/parametres': typeof ParametresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annees'
    | '/bulletins'
    | '/classes'
    | '/eleves'
    | '/matieres'
    | '/notes'
    | '/parametres'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annees'
    | '/bulletins'
    | '/classes'
    | '/eleves'
    | '/matieres'
    | '/notes'
    | '/parametres'
  id:
    | '__root__'
    | '/'
    | '/annees'
    | '/bulletins'
    | '/classes'
    | '/eleves'
    | '/matieres'
    | '/notes'
    | '/parametres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnneesRoute: typeof AnneesRoute
  BulletinsRoute: typeof BulletinsRoute
  ClassesRoute: typeof ClassesRoute
  ElevesRoute: typeof ElevesRoute
  MatieresRoute: typeof MatieresRoute
  NotesRoute: typeof NotesRoute
  ParametresRoute: typeof ParametresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annees': {
      id: '/annees'
      path: '/annees'
      fullPath: '/annees'
      preLoaderRoute: typeof AnneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletins': {
      id: '/bulletins'
      path: '/bulletins'
      fullPath: '/bulletins'
      preLoaderRoute: typeof BulletinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves': {
      id: '/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof ElevesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matieres': {
      id: '/matieres'
      path: '/matieres'
      fullPath: '/matieres'
      preLoaderRoute: typeof MatieresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnneesRoute: AnneesRoute,
  BulletinsRoute: BulletinsRoute,
  ClassesRoute: ClassesRoute,
  ElevesRoute: ElevesRoute,
  MatieresRoute: MatieresRoute,
  NotesRoute: NotesRoute,
  ParametresRoute: ParametresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
